# Generated by Django 4.2 on 2023-12-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('paragraph', models.TextField()),
                ('predicted_pabel', models.CharField(max_length=255, verbose_name='Predicted Pabel')),
                ('scores', models.FloatField(default=0)),
                ('sentiment', models.CharField(max_length=255)),
                ('uuid', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
