# Generated by Django 4.2 on 2023-12-31 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0002_data_champ_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='champ_date',
        ),
    ]
