# Generated by Django 4.2 on 2024-01-01 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0004_data_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='release_date',
        ),
    ]
