# Generated by Django 4.2 on 2024-01-01 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0005_remove_data_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
